=== mahmoudhassanamin/XML/lab2/task 4/newXmlSchema.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="BookStore" type="BookStoreType"/>
    <xs:complexType name="BookStoreType">
        <xs:sequence>
            <xs:element name="book" type="bookType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element name="Title" type="xs:string"/>
            <xs:element name="Author" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="Category" type="categoryType" default="fiction"/>
        <xs:attribute name="InStock" type="InStockType" default="false"/>
    </xs:complexType>
    <xs:simpleType name="categoryType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="science"/>
            <xs:enumeration value="fiction"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="InStockType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== mahmoudhassanamin/XML/lab2/task 4/BookStore2.xml
<?xml version="1.0" encoding="UTF-8"?>

<BookStore
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="newXmlSchema.xsd">
    <book Category="science" InStock="false">
        <Title>jungel book</Title>
        <Author>ahmed</Author>
    </book>
    <book Category="fiction">
        <Title>jungel book</Title>
        <Author>ahmed</Author>
    </book>
    <book InStock="true">
        <Title>jungel book</Title>
        <Author>ahmed</Author>
    </book>
</BookStore>
