=== mahmoudhassanamin/XML/lab2/task 2/newXmlSchema.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="library" type="libType"/>
    <xs:complexType name="libType">
        <xs:sequence>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="librarian" type="xs:string"/>
            <xs:element name="book" type="bookType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="location" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element name="author" type="xs:string"/>
            <xs:element name="preface" type="xs:string"/>
            <xs:element name="part" type="partType" minOccurs="1" maxOccurs="100"/>
        </xs:sequence>
         <xs:attribute name="ISBN" type="xs:integer" use="required"/>
    </xs:complexType>
    <xs:complexType name="partType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="chapter" type="chapterType" minOccurs="1" maxOccurs="1000"/>
        </xs:sequence>
         <xs:attribute name="number" type="xs:integer" use="required"/>
    </xs:complexType>
    <xs:complexType name="chapterType">
        <xs:sequence>
            <xs:element name="chpterTitle" type="xs:string"/>
            <xs:element name="summary" type="xs:string"/>
            <xs:element name="section" type="sectionType" minOccurs="1" maxOccurs="1000"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="sectionType">
        <xs:sequence>
            <xs:element name="content" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== mahmoudhassanamin/XML/lab2/task 2/liberary.xml
<?xml version="1.0" encoding="UTF-8"?>

<library location="egypt-alex-elagami"
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="newXmlSchema.xsd">
    <description>beautiful lib</description>
    <librarian>mahmoud hassan amin</librarian>
    <book ISBN="1234">
        <author>ahmed</author>
        <preface>jungel book</preface>
        <part number="1">
            <title>intro</title>
            <chapter>
                <chpterTitle>one</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
            <chapter>
                <chpterTitle>two</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
        </part>
        <part number="2">
            <title>intro</title>
            <chapter>
                <chpterTitle>one</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
            <chapter>
                <chpterTitle>two</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
        </part>
    </book>
    <book ISBN="5678">
        <author>ahmed</author>
        <preface>jungel book</preface>
        <part number="1">
            <title>intro</title>
            <chapter>
                <chpterTitle>one</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
            <chapter>
                <chpterTitle>two</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
        </part>
        <part number="2">
            <title>intro</title>
            <chapter>
                <chpterTitle>one</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
            <chapter>
                <chpterTitle>two</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
        </part>
    </book>
</library>
