=== mahmoudhassanamin/XML/lab1/task1.dtd
<!ELEMENT library (description,librarian,book*)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT librarian (#PCDATA)>
<!ELEMENT book (author,preface,part+)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT preface (#PCDATA)>
<!ELEMENT part (title,chapter+)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT chapter (chpterTitle,summary,section+)>
<!ELEMENT chpterTitle (#PCDATA)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT section (content)>
<!ELEMENT content (#PCDATA)>
<!ATTLIST library location CDATA #REQUIRED>
<!ATTLIST book ISBN ID #REQUIRED>
<!ATTLIST part number CDATA #IMPLIED>

=== mahmoudhassanamin/XML/lab1/task1.xml
<?xml version="1.0"?>
<!DOCTYPE library SYSTEM "task1.dtd">

<library location="egypt-alex-elagami">
    <description>beautiful lib</description>
    <librarian>mahmoud hassan amin</librarian>
    <book ISBN="1234">
        <author>ahmed</author>
        <preface>jungel book</preface>
        <part number="1">
            <title>intro</title>
            <chapter>
                <chpterTitle>one</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
            <chapter>
                <chpterTitle>two</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
        </part>
        <part number="2">
            <title>intro</title>
            <chapter>
                <chpterTitle>one</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
            <chapter>
                <chpterTitle>two</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
        </part>
    </book>
    <book ISBN="5678">
        <author>ahmed</author>
        <preface>jungel book</preface>
        <part number="1">
            <title>intro</title>
            <chapter>
                <chpterTitle>one</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
            <chapter>
                <chpterTitle>two</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
        </part>
        <part number="2">
            <title>intro</title>
            <chapter>
                <chpterTitle>one</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
            <chapter>
                <chpterTitle>two</chpterTitle>
                <summary>blablabla</summary>
                <section>
                    <content>kan ya ma kan</content>
                </section>
                <section>
                    <content>kan ya ma kan</content>
                </section>
            </chapter>
        </part>
    </book>
</library>
