=== mahmoudhassanamin/XML/lab2/task 3/newXmlSchema.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="BookStore" type="BookStoreType"/>
    <xs:complexType name="BookStoreType">
        <xs:sequence>
            <xs:element name="book" type="bookType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="bookType">
        <xs:sequence>
            <xs:element name="Title" type="xs:string"/>
            <xs:element name="Author" type="xs:string"/>
            <xs:element name="Date" type="xs:date"/>
            <xs:element name="ISBN" type="xs:integer"/>
            <xs:element name="Publisher" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== mahmoudhassanamin/XML/lab2/task 3/BookStore.xml
<?xml version="1.0" encoding="UTF-8"?>

<BookStore
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="newXmlSchema.xsd">
    <book>
        <Title>jungel book</Title>
        <Author>ahmed</Author>
        <Date>2002-05-30</Date>
        <ISBN>12344</ISBN>
        <Publisher>dar el nashr</Publisher>
    </book>
    <book>
        <Title>jungel book2</Title>
        <Author>ahmed</Author>
        <Date>2002-05-30</Date>
        <ISBN>12344</ISBN>
        <Publisher>dar el nashr</Publisher>
    </book>
</BookStore>
